from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

from simulator.common.validation import (
    validate_fraction as _validate_fraction,
)
from simulator.common.validation import (
    validate_non_negative_scalar as _validate_non_negative_float,
)
from simulator.common.validation import (
    validate_numeric_scalar as _validate_numeric_scalar,
)
from simulator.common.validation import (
    validate_positive_int as _validate_positive_int,
)
from simulator.common.validation import (
    validate_spatial_float_array as _validate_spatial_float_array,
)
from simulator.core.types import FloatArray, SimulationDomain


@dataclass(frozen=True)
class TemperatureFieldConfig:
    """Configuration of the spatial air-temperature anomaly field.

    The field represents a low-amplitude, smooth spatial perturbation added to
    the regional background temperature generated by the latent environment.

    The perturbation has zero spatial mean, so it redistributes temperature
    within the domain without changing the scenario's domain-mean temperature.
    """

    enabled: bool = True
    """
    Activates or deactivates the spatial anomaly.
    """

    random_seed: int = 8642
    """
    It controls the randomness of the temperature model.
    """

    gradient_amplitude_c: float = 0.75
    """
    It controls the amplitude of the main temperature gradient.
    """

    smooth_anomaly_amplitude_c: float = 0.20
    """
    It controls a second component of the anomaly: an additional smooth spatial variation.
    """

    smooth_anomaly_smoothing_passes: int = 8
    """
    It controls how many times the secondary component is smoothed.
    """

    orientation_change_probability: float = 0.003
    """
    It controls the probability that the model decides to change the gradient orientation in a time step.
    """

    transition_steps: int = 12
    """
    It controls how many steps it takes the model to switch from an old orientation to a new one.
    """

    def __post_init__(self) -> None:
        if not isinstance(self.enabled, bool):
            raise TypeError(f"'enabled' must be bool, got {type(self.enabled).__name__}")

        if not isinstance(self.random_seed, int):
            raise TypeError(f"'random_seed' must be int, got {type(self.random_seed).__name__}")

        _validate_non_negative_float("gradient_amplitude_c", self.gradient_amplitude_c)
        _validate_non_negative_float("smooth_anomaly_amplitude_c", self.smooth_anomaly_amplitude_c)

        if not isinstance(self.smooth_anomaly_smoothing_passes, int):
            raise TypeError(
                f"'smooth_anomaly_smoothing_passes' must be int, got {type(self.smooth_anomaly_smoothing_passes).__name__}"
            )
        if self.smooth_anomaly_smoothing_passes < 0:
            raise ValueError(f"'smooth_anomaly_smoothing_passes' must be >= 0, got {self.smooth_anomaly_smoothing_passes}")

        _validate_fraction("orientation_change_probability", self.orientation_change_probability)
        _validate_positive_int("transition_steps", self.transition_steps)


@dataclass(frozen=True)
class TemperatureFieldState:
    """Persistent state of the spatial temperature anomaly model."""

    active_anomaly_c: FloatArray
    """
    Anomaly field that is currently in use.
    """

    source_anomaly_c: FloatArray | None
    """
    It stores the origin anomaly when a transition is in progress.
    """

    target_anomaly_c: FloatArray | None
    """
    It stores the target anomaly when there is a transition.
    """

    transition_step: int
    """
    Indicate what stage of the transition we are at.
    """

    def __post_init__(self) -> None:
        _validate_spatial_float_array("active_anomaly_c", self.active_anomaly_c)

        if self.source_anomaly_c is not None:
            _validate_spatial_float_array("source_anomaly_c", self.source_anomaly_c)
            if self.source_anomaly_c.shape != self.active_anomaly_c.shape:
                raise ValueError(
                    "'source_anomaly_c' must have the same shape as 'active_anomaly_c', "
                    f"got {self.source_anomaly_c.shape} and {self.active_anomaly_c.shape}"
                )

        if self.target_anomaly_c is not None:
            _validate_spatial_float_array("target_anomaly_c", self.target_anomaly_c)
            if self.target_anomaly_c.shape != self.active_anomaly_c.shape:
                raise ValueError(
                    "'target_anomaly_c' must have the same shape as 'active_anomaly_c', "
                    f"got {self.target_anomaly_c.shape} and {self.active_anomaly_c.shape}"
                )

        if not isinstance(self.transition_step, int) or self.transition_step < 0:
            raise ValueError(f"'transition_step' must be a non-negative int, got {self.transition_step!r}")


class TemperatureFieldModel:
    """Stateful generator of smooth spatial air-temperature fields."""

    def __init__(self, config: TemperatureFieldConfig) -> None:
        if not isinstance(config, TemperatureFieldConfig):
            raise TypeError(f"'config' must be a TemperatureFieldConfig, got {type(config).__name__}")

        self.config = config
        self._rng = np.random.default_rng(config.random_seed)
        self._latest_state: TemperatureFieldState | None = None

    @property
    def latest_state(self) -> TemperatureFieldState | None:
        """Return the latest internal state of the temperature anomaly model."""
        return self._latest_state

    def reset(self) -> None:
        """Reset RNG and persistent state to their initial reproducible state."""
        self._rng = np.random.default_rng(self.config.random_seed)
        self._latest_state = None

    def step(
        self,
        *,
        domain: SimulationDomain,
        background_temperature_c: int | float,
    ) -> FloatArray:
        """Build the 2D air-temperature field for one simulation step."""
        if not isinstance(domain, SimulationDomain):
            raise TypeError(f"'domain' must be a SimulationDomain, got {type(domain).__name__}")

        background_temperature_c = _validate_numeric_scalar(
            "background_temperature_c",
            background_temperature_c,
        )

        if not self.config.enabled:
            return np.full(domain.shape, background_temperature_c, dtype=float)

        anomaly_c = self._update_anomaly(domain)
        return (background_temperature_c + anomaly_c).astype(float, copy=False)

    def _update_anomaly(self, domain: SimulationDomain) -> FloatArray:
        """Update and return the current smooth spatial anomaly."""
        if self._latest_state is None:
            active_anomaly = self._sample_anomaly(domain)
            self._latest_state = TemperatureFieldState(
                active_anomaly_c=active_anomaly,
                source_anomaly_c=None,
                target_anomaly_c=None,
                transition_step=0,
            )
            return active_anomaly

        state = self._latest_state

        if self._is_transitioning(state):
            active_anomaly, next_state = self._advance_transition(state)
            self._latest_state = next_state
            return active_anomaly

        if self._rng.random() < self.config.orientation_change_probability:
            target_anomaly = self._sample_anomaly(domain)
            transition_state = TemperatureFieldState(
                active_anomaly_c=state.active_anomaly_c,
                source_anomaly_c=state.active_anomaly_c,
                target_anomaly_c=target_anomaly,
                transition_step=0,
            )
            active_anomaly, next_state = self._advance_transition(transition_state)
            self._latest_state = next_state
            return active_anomaly

        return state.active_anomaly_c

    @staticmethod
    def _is_transitioning(state: TemperatureFieldState) -> bool:
        return state.source_anomaly_c is not None and state.target_anomaly_c is not None

    def _advance_transition(
        self,
        state: TemperatureFieldState,
    ) -> tuple[FloatArray, TemperatureFieldState]:
        """Advance one step in a smooth anomaly transition."""
        assert state.source_anomaly_c is not None
        assert state.target_anomaly_c is not None

        next_transition_step = state.transition_step + 1
        weight = min(1.0, next_transition_step / self.config.transition_steps)

        active_anomaly = (1.0 - weight) * state.source_anomaly_c + weight * state.target_anomaly_c
        active_anomaly = self._zero_mean(active_anomaly)

        if weight >= 1.0:
            next_state = TemperatureFieldState(
                active_anomaly_c=state.target_anomaly_c,
                source_anomaly_c=None,
                target_anomaly_c=None,
                transition_step=0,
            )
        else:
            next_state = TemperatureFieldState(
                active_anomaly_c=active_anomaly,
                source_anomaly_c=state.source_anomaly_c,
                target_anomaly_c=state.target_anomaly_c,
                transition_step=next_transition_step,
            )

        return active_anomaly, next_state

    def _sample_anomaly(self, domain: SimulationDomain) -> FloatArray:
        """Sample one smooth, zero-mean spatial anomaly pattern."""
        gradient = self._sample_oriented_gradient(domain)
        smooth_component = self._sample_smooth_component(domain)

        anomaly = self.config.gradient_amplitude_c * gradient + self.config.smooth_anomaly_amplitude_c * smooth_component

        return self._zero_mean(anomaly)

    def _sample_oriented_gradient(self, domain: SimulationDomain) -> FloatArray:
        """Sample a normalized linear gradient with random orientation."""
        x_norm, y_norm = self._normalized_coordinate_grids(domain)

        theta = float(self._rng.uniform(0.0, 2.0 * math.pi))
        gradient = math.cos(theta) * x_norm + math.sin(theta) * y_norm

        return self._normalize_signed_field(gradient)

    def _sample_smooth_component(self, domain: SimulationDomain) -> FloatArray:
        """Sample a smooth zero-mean secondary anomaly component."""
        raw = self._rng.normal(0.0, 1.0, size=domain.shape)
        smoothed = raw.astype(float, copy=True)

        for _ in range(self.config.smooth_anomaly_smoothing_passes):
            smoothed = self._box_smooth_once(smoothed)

        return self._normalize_signed_field(smoothed)

    @staticmethod
    def _normalized_coordinate_grids(domain: SimulationDomain) -> tuple[FloatArray, FloatArray]:
        """Return x/y coordinate grids normalized approximately into [-1, 1]."""
        x_coords = domain.spatial.x_coords.astype(float, copy=False)
        y_coords = domain.spatial.y_coords.astype(float, copy=False)

        x_center = 0.5 * (float(x_coords[0]) + float(x_coords[-1]))
        y_center = 0.5 * (float(y_coords[0]) + float(y_coords[-1]))

        x_half_range = max(0.5 * (float(x_coords[-1]) - float(x_coords[0])), 1e-12)
        y_half_range = max(0.5 * (float(y_coords[-1]) - float(y_coords[0])), 1e-12)

        x_norm_1d = (x_coords - x_center) / x_half_range
        y_norm_1d = (y_coords - y_center) / y_half_range

        x_grid, y_grid = np.meshgrid(x_norm_1d, y_norm_1d)
        return x_grid.astype(float, copy=False), y_grid.astype(float, copy=False)

    @staticmethod
    def _normalize_signed_field(field: FloatArray) -> FloatArray:
        """Normalize a field to zero mean and maximum absolute value 1."""
        centered = TemperatureFieldModel._zero_mean(field)
        max_abs = float(np.max(np.abs(centered)))

        if max_abs <= 0.0:
            return np.zeros_like(centered, dtype=float)

        return (centered / max_abs).astype(float, copy=False)

    @staticmethod
    def _zero_mean(field: FloatArray) -> FloatArray:
        """Return a copy of field with zero spatial mean."""
        return (field - float(np.mean(field))).astype(float, copy=False)

    @staticmethod
    def _box_smooth_once(field: FloatArray) -> FloatArray:
        """Apply one 3x3 box filter using edge padding."""
        padded = np.pad(field, pad_width=1, mode="edge")

        smoothed = (
            padded[:-2, :-2]
            + padded[:-2, 1:-1]
            + padded[:-2, 2:]
            + padded[1:-1, :-2]
            + padded[1:-1, 1:-1]
            + padded[1:-1, 2:]
            + padded[2:, :-2]
            + padded[2:, 1:-1]
            + padded[2:, 2:]
        ) / 9.0

        return smoothed.astype(float, copy=False)


def build_air_temperature_field(
    domain: SimulationDomain,
    background_temperature_c: int | float,
    model: TemperatureFieldModel | None = None,
) -> FloatArray:
    """Compatibility helper for building air-temperature fields."""
    if model is None:
        background_temperature_c = _validate_numeric_scalar(
            "background_temperature_c",
            background_temperature_c,
        )
        return np.full(domain.shape, background_temperature_c, dtype=float)

    return model.step(
        domain=domain,
        background_temperature_c=background_temperature_c,
    )
