grid:
  nx: 80
  ny: 60
  dx: 1000.0
  dy: 1000.0
  x0: 0.0
  y0: 0.0

reservoirs:
    - name: upper_reservoir
      cell_y: 15
      cell_x: 20
      capacity: 3000000.0
      initial_storage: 1800000.0

    - name: middle_reservoir
      cell_y: 35
      cell_x: 50
      capacity: 5000000.0
      initial_storage: 2500000.0

sensors: []
