from __future__ import annotations

import argparse
import csv
import pickle
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import xarray as xr


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI parser for figure generation."""
    parser = argparse.ArgumentParser(
        prog="hydro-sim-plot",
        description="Genera figuras a partir de una ejecución existente del simulador.",
    )
    parser.add_argument(
        "--run-dir",
        type=Path,
        required=True,
        help="Ruta a un directorio de salida de una ejecución, por ejemplo outputs/runs/base_run",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directorio opcional de salida de figuras. Por defecto: <run-dir>/figures",
    )
    return parser


def _parse_csv_float(value: str) -> float:
    """Parse one float from the project CSV format."""
    text = value.strip()

    if text == "":
        return float("nan")

    lowered = text.lower()
    if lowered in {"nan", "none"}:
        return float("nan")

    return float(text.replace(",", "."))


def _parse_csv_int(value: str) -> int:
    """Parse one integer from CSV."""
    text = value.strip()

    if text == "":
        raise ValueError("No se puede interpretar una cadena vacía como entero")

    return int(text)


def _read_semicolon_csv(path: Path) -> list[dict[str, str]]:
    """Read one project CSV file using ';' as delimiter."""
    if not path.exists():
        raise FileNotFoundError(f"No se encontró el archivo CSV requerido: {path}")

    with path.open("r", newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file, delimiter=";")
        return list(reader)


def _read_summary_rows(path: Path) -> list[dict[str, object]]:
    """Read and type-cast the step-summary CSV generated by the runner."""
    raw_rows = _read_semicolon_csv(path)

    parsed_rows: list[dict[str, object]] = []
    for row in raw_rows:
        parsed_rows.append(
            {
                "step": _parse_csv_int(row["step"]),
                "timestamp": row["timestamp"].strip(),
                "regime": row["regime"].strip(),
                "new_storms": _parse_csv_int(row["new_storms"]),
                "tracked_storms": _parse_csv_int(row["tracked_storms"]),
                "precipitation_sum_mm_dt": _parse_csv_float(row["precipitation_sum_mm_dt"]),
                "precipitation_max_mm_dt": _parse_csv_float(row["precipitation_max_mm_dt"]),
                "background_precipitation_sum_mm_dt": _parse_csv_float(row["background_precipitation_sum_mm_dt"]),
                "background_precipitation_max_mm_dt": _parse_csv_float(row["background_precipitation_max_mm_dt"]),
                "background_fraction_of_total": _parse_csv_float(row["background_fraction_of_total"]),
                "background_activity_factor": _parse_csv_float(row["background_activity_factor"]),
                "precipitation_spell_index": _parse_csv_float(row["precipitation_spell_index"]),
                "band_reorganization_applied": _parse_csv_int(row["band_reorganization_applied"]),
                "band_births_count": _parse_csv_int(row["band_births_count"]),
                "band_probability": _parse_csv_float(row["band_probability"]),
                "storm_mask_active_cells": _parse_csv_int(row["storm_mask_active_cells"]),
                "air_temperature_min_c": _parse_csv_float(row["air_temperature_min_c"]),
                "air_temperature_mean_c": _parse_csv_float(row["air_temperature_mean_c"]),
                "air_temperature_max_c": _parse_csv_float(row["air_temperature_max_c"]),
                "air_temperature_range_c": _parse_csv_float(row["air_temperature_range_c"]),
                "pet_mean_mm_dt": _parse_csv_float(row["pet_mean_mm_dt"]),
                "shortwave_radiation_mean_w_m2": _parse_csv_float(row["shortwave_radiation_mean_w_m2"]),
                "net_radiation_mean_mj_m2_dt": _parse_csv_float(row["net_radiation_mean_mj_m2_dt"]),
                "aet_mean_mm_dt": _parse_csv_float(row["aet_mean_mm_dt"]),
                "soil_moisture_mean_mm": _parse_csv_float(row["soil_moisture_mean_mm"]),
                "infiltration_sum_mm_dt": _parse_csv_float(row["infiltration_sum_mm_dt"]),
                "surface_runoff_sum_mm_dt": _parse_csv_float(row["surface_runoff_sum_mm_dt"]),
                "subsurface_runoff_sum_mm_dt": _parse_csv_float(row["subsurface_runoff_sum_mm_dt"]),
                "channel_flow_mean_m3s": _parse_csv_float(row["channel_flow_mean_m3s"]),
                "channel_flow_max_m3s": _parse_csv_float(row["channel_flow_max_m3s"]),
                "outlet_discharge_m3s": _parse_csv_float(row["outlet_discharge_m3s"]),
                "reservoir_inflow_sum_m3s": _parse_csv_float(row["reservoir_inflow_sum_m3s"]),
                "reservoir_release_sum_m3s": _parse_csv_float(row["reservoir_release_sum_m3s"]),
                "reservoir_spill_sum_m3s": _parse_csv_float(row["reservoir_spill_sum_m3s"]),
                "reservoir_storage_sum_m3": _parse_csv_float(row["reservoir_storage_sum_m3"]),
                "obs_available_count": _parse_csv_int(row["obs_available_count"]),
                "obs_missing_count": _parse_csv_int(row["obs_missing_count"]),
                "obs_censored_count": _parse_csv_int(row["obs_censored_count"]),
            }
        )

    return parsed_rows


def _read_observation_rows(path: Path) -> list[dict[str, object]]:
    """Read and type-cast the observation CSV generated by the runner."""
    raw_rows = _read_semicolon_csv(path)

    parsed_rows: list[dict[str, object]] = []
    for row in raw_rows:
        parsed_rows.append(
            {
                "step": _parse_csv_int(row["step"]),
                "timestamp": row["timestamp"].strip(),
                "sensor_index": _parse_csv_int(row["sensor_index"]),
                "sensor_name": row["sensor_name"].strip(),
                "sensor_type": row["sensor_type"].strip(),
                "cell_y": _parse_csv_int(row["cell_y"]),
                "cell_x": _parse_csv_int(row["cell_x"]),
                "truth_value": _parse_csv_float(row["truth_value"]),
                "observed_value": _parse_csv_float(row["observed_value"]),
                "observation_available": _parse_csv_int(row["observation_available"]),
                "quality_flag": _parse_csv_int(row["quality_flag"]),
                "quality_label": row["quality_label"].strip(),
            }
        )

    return parsed_rows


def _resolve_single_matching_file(
    run_dir: Path,
    *,
    canonical_names: tuple[str, ...],
    glob_patterns: tuple[str, ...],
    excluded_stem_suffixes: tuple[str, ...] = (),
) -> Path:
    """Resolve one run artifact from canonical names or scenario-suffixed patterns."""
    for name in canonical_names:
        path = run_dir / name
        if path.exists():
            return path

    candidates: set[Path] = set()
    for pattern in glob_patterns:
        candidates.update(run_dir.glob(pattern))

    filtered_candidates = sorted(
        path for path in candidates if path.is_file() and not any(path.stem.endswith(suffix) for suffix in excluded_stem_suffixes)
    )

    if not filtered_candidates:
        expected = ", ".join(canonical_names + glob_patterns)
        raise FileNotFoundError(f"No se encontró ningún artefacto de ejecución en {run_dir}. Esperado: {expected}")

    if len(filtered_candidates) > 1:
        candidates_text = "\n".join(f"- {path}" for path in filtered_candidates)
        raise RuntimeError(
            "Se encontraron varios artefactos de ejecución compatibles. "
            "Usa un directorio con un único escenario o se más preciso.\n"
            f"{candidates_text}"
        )

    return filtered_candidates[0]


def _resolve_csv_for_scenario(
    run_dir: Path,
    *,
    base_stem: str,
    scenario_name: str | None,
) -> Path:
    """Resolve the English CSV matching the scenario stored in the truth dataset."""
    if scenario_name:
        scenario_path = run_dir / f"{base_stem}_{scenario_name}.csv"
        if scenario_path.exists():
            return scenario_path

        legacy_path = run_dir / f"{base_stem}.csv"
        if legacy_path.exists():
            return legacy_path

        raise FileNotFoundError(
            f"No se encontró el CSV para el escenario {scenario_name!r}. "
            f"Se esperaba {scenario_path} o el archivo heredado {legacy_path}"
        )

    return _resolve_single_matching_file(
        run_dir,
        canonical_names=(f"{base_stem}.csv",),
        glob_patterns=(f"{base_stem}_*.csv",),
        excluded_stem_suffixes=("_es",),
    )


def _load_truth_dataset(run_dir: Path) -> tuple[xr.Dataset, Path]:
    """Load the truth dataset from NetCDF or pickle."""
    dataset_path = _resolve_single_matching_file(
        run_dir,
        canonical_names=(
            "simulation_truth.nc",
            "simulation_truth.pkl",
        ),
        glob_patterns=(
            "simulation_truth_*.nc",
            "simulation_truth_*.pkl",
        ),
    )

    if dataset_path.suffix == ".nc":
        return xr.open_dataset(dataset_path), dataset_path

    if dataset_path.suffix == ".pkl":
        with dataset_path.open("rb") as file:
            ds = pickle.load(file)

        if not isinstance(ds, xr.Dataset):
            raise TypeError(f"El archivo pickle no contiene un xarray.Dataset: {dataset_path}")

        return ds, dataset_path

    raise ValueError(f"Formato de dataset de verdad no soportado: {dataset_path}")


SENSOR_TYPE_LABELS_ES: dict[str, str] = {
    "precipitation": "precipitación",
    "discharge": "caudal",
    "reservoir_storage": "almacenamiento en embalse",
}


def _safe_filename(text: str) -> str:
    """Convert a free-text label into a safe filename stem."""
    normalized = text.strip().lower()
    normalized = re.sub(r"\s+", "_", normalized)
    normalized = re.sub(r"[^a-z0-9_]+", "", normalized)
    return normalized or "unnamed"


def _format_sensor_name_for_plot(sensor_name: str) -> str:
    """Return a human-friendly sensor name for plot titles."""
    return sensor_name.strip().replace("_", " ")


def _format_sensor_type_for_plot(sensor_type: str) -> str:
    """Return a Spanish sensor-type label for plot titles."""
    normalized = sensor_type.strip().lower()
    return SENSOR_TYPE_LABELS_ES.get(normalized, sensor_type)


def _save_field_plot(
    field: np.ndarray,
    *,
    title: str,
    output_path: Path,
    colorbar_label: str,
) -> None:
    """Save one 2D field as a PNG image."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(8, 6))
    image = plt.imshow(field, origin="lower")
    plt.title(title)
    plt.xlabel("x")
    plt.ylabel("y")
    plt.colorbar(image, label=colorbar_label)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()


def _save_line_plot(
    x: np.ndarray,
    y: np.ndarray,
    *,
    title: str,
    xlabel: str,
    ylabel: str,
    output_path: Path,
) -> None:
    """Save one simple line plot as a PNG image."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(8, 4.5))
    plt.plot(x, y)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()


def _save_sensor_truth_vs_observed_plot(
    rows: list[dict[str, object]],
    *,
    output_path: Path,
) -> None:
    """Save one sensor plot comparing truth and observed values over time."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    rows_sorted = sorted(rows, key=lambda row: int(row["step"]))

    steps = np.asarray([int(row["step"]) for row in rows_sorted], dtype=int)
    truth = np.asarray([float(row["truth_value"]) for row in rows_sorted], dtype=float)
    observed = np.asarray([float(row["observed_value"]) for row in rows_sorted], dtype=float)

    first = rows_sorted[0]
    sensor_name = _format_sensor_name_for_plot(str(first["sensor_name"]))
    sensor_type = _format_sensor_type_for_plot(str(first["sensor_type"]))

    plt.figure(figsize=(9, 4.5))
    plt.plot(steps, truth, label="verdad")
    plt.plot(steps, observed, label="observado")
    plt.title(f"Verdad vs observado - {sensor_name} ({sensor_type})")
    plt.xlabel("paso")
    plt.ylabel("valor")
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()


def _generate_field_plots(
    *,
    truth_ds: xr.Dataset,
    output_dir: Path,
) -> None:
    """Generate spatial field plots aggregated over the whole run."""
    fields_dir = output_dir / "fields"
    fields_dir.mkdir(parents=True, exist_ok=True)

    precipitation = np.asarray(truth_ds["precipitation"].values, dtype=float)
    background_precipitation = np.asarray(truth_ds["background_precipitation"].values, dtype=float)

    pet = np.asarray(truth_ds["pet"].values, dtype=float)
    aet = np.asarray(truth_ds["aet"].values, dtype=float)
    shortwave_radiation = np.asarray(truth_ds["shortwave_radiation"].values, dtype=float)
    net_radiation = np.asarray(truth_ds["net_radiation"].values, dtype=float)

    soil_moisture = np.asarray(truth_ds["soil_moisture"].values, dtype=float)
    infiltration = np.asarray(truth_ds["infiltration"].values, dtype=float)
    surface_runoff = np.asarray(truth_ds["surface_runoff"].values, dtype=float)
    subsurface_runoff = np.asarray(truth_ds["subsurface_runoff"].values, dtype=float)

    accumulated_precipitation = np.nansum(precipitation, axis=0)
    accumulated_background_precipitation = np.nansum(background_precipitation, axis=0)
    accumulated_pet = np.nansum(pet, axis=0)
    accumulated_aet = np.nansum(aet, axis=0)
    accumulated_infiltration = np.nansum(infiltration, axis=0)
    accumulated_surface_runoff = np.nansum(surface_runoff, axis=0)
    accumulated_subsurface_runoff = np.nansum(subsurface_runoff, axis=0)

    mean_shortwave_radiation = np.nanmean(shortwave_radiation, axis=0)
    mean_net_radiation = np.nanmean(net_radiation, axis=0)
    mean_soil_moisture = np.nanmean(soil_moisture, axis=0)
    final_soil_moisture = soil_moisture[-1] if soil_moisture.shape[0] > 0 else np.zeros(soil_moisture.shape[1:], dtype=float)

    _save_field_plot(
        accumulated_precipitation,
        title="Precipitación acumulada",
        output_path=fields_dir / "accumulated_precipitation.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_background_precipitation,
        title="Precipitación de fondo acumulada",
        output_path=fields_dir / "accumulated_background_precipitation.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_pet,
        title="PET acumulada",
        output_path=fields_dir / "accumulated_pet.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_aet,
        title="AET acumulada",
        output_path=fields_dir / "accumulated_aet.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_infiltration,
        title="Infiltración acumulada",
        output_path=fields_dir / "accumulated_infiltration.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_surface_runoff,
        title="Escorrentía superficial acumulada",
        output_path=fields_dir / "accumulated_surface_runoff.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_subsurface_runoff,
        title="Escorrentía subsuperficial acumulada",
        output_path=fields_dir / "accumulated_subsurface_runoff.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        mean_soil_moisture,
        title="Humedad media del suelo",
        output_path=fields_dir / "mean_soil_moisture.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        final_soil_moisture,
        title="Humedad final del suelo",
        output_path=fields_dir / "final_soil_moisture.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        mean_shortwave_radiation,
        title="Radiación de onda corta media",
        output_path=fields_dir / "mean_shortwave_radiation.png",
        colorbar_label="W/m2",
    )
    _save_field_plot(
        mean_net_radiation,
        title="Radiación neta media",
        output_path=fields_dir / "mean_net_radiation.png",
        colorbar_label="MJ/m2/dt",
    )


def _generate_peak_step_plots(
    *,
    truth_ds: xr.Dataset,
    summary_rows: list[dict[str, object]],
    output_dir: Path,
) -> None:
    """Generate peak-step and special-step spatial plots."""
    fields_dir = output_dir / "fields"
    fields_dir.mkdir(parents=True, exist_ok=True)

    precipitation = np.asarray(truth_ds["precipitation"].values, dtype=float)
    storm_mask = np.asarray(truth_ds["storm_mask"].values, dtype=bool)
    infiltration = np.asarray(truth_ds["infiltration"].values, dtype=float)
    surface_runoff = np.asarray(truth_ds["surface_runoff"].values, dtype=float)
    soil_moisture = np.asarray(truth_ds["soil_moisture"].values, dtype=float)
    channel_flow = np.asarray(truth_ds["channel_flow"].values, dtype=float)

    if precipitation.shape[0] > 0 and np.isfinite(precipitation).any():
        peak_precip_step = int(np.nanargmax(np.nanmax(precipitation, axis=(1, 2))))

        _save_field_plot(
            precipitation[peak_precip_step],
            title=f"Paso de máxima precipitación: {peak_precip_step}",
            output_path=fields_dir / "step_peak_precipitation.png",
            colorbar_label="mm/dt",
        )
        _save_field_plot(
            storm_mask[peak_precip_step].astype(float),
            title=f"Máscara de tormenta en el paso de máxima precipitacion - Paso: {peak_precip_step}",
            output_path=fields_dir / "step_peak_storm_mask.png",
            colorbar_label="1",
        )

    if surface_runoff.shape[0] > 0 and np.isfinite(surface_runoff).any():
        peak_runoff_step = int(np.nanargmax(np.nanmax(surface_runoff, axis=(1, 2))))

        _save_field_plot(
            surface_runoff[peak_runoff_step],
            title=f"Paso de máxima escorrentía superficial: {peak_runoff_step}",
            output_path=fields_dir / "step_peak_surface_runoff.png",
            colorbar_label="mm/dt",
        )
        _save_field_plot(
            infiltration[peak_runoff_step],
            title=f"Infiltración en el paso de máxima escorrentía superficial - Paso: {peak_runoff_step}",
            output_path=fields_dir / "step_peak_infiltration.png",
            colorbar_label="mm/dt",
        )
        _save_field_plot(
            soil_moisture[peak_runoff_step],
            title=f"Humedad del suelo en el paso de máxima escorrentía superficial - Paso: {peak_runoff_step}",
            output_path=fields_dir / "step_peak_runoff_soil_moisture.png",
            colorbar_label="mm",
        )
        _save_field_plot(
            channel_flow[peak_runoff_step],
            title=f"Caudal en el cauce en el paso de máxima escorrentía superficial - Paso: {peak_runoff_step}",
            output_path=fields_dir / "step_peak_channel_flow.png",
            colorbar_label="m3/s",
        )

    if summary_rows and "band_reorganization_applied" in summary_rows[0]:
        band_steps = [int(row["step"]) for row in summary_rows if int(row["band_reorganization_applied"]) == 1]

        if band_steps:
            first_band_step = band_steps[0]

            _save_field_plot(
                precipitation[first_band_step],
                title=f"Precipitación en primer paso con organización en banda - Paso: {first_band_step}",
                output_path=fields_dir / "step_first_band_precipitation.png",
                colorbar_label="mm/dt",
            )
            _save_field_plot(
                storm_mask[first_band_step].astype(float),
                title=f"Máscara de tormenta en primer paso con organización en banda - Paso: {first_band_step}",
                output_path=fields_dir / "step_first_band_storm_mask.png",
                colorbar_label="1",
            )


def _generate_summary_plots(
    *,
    summary_rows: list[dict[str, object]],
    output_dir: Path,
) -> None:
    """Generate time-series plots from the step summary CSV."""
    summary_dir = output_dir / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)

    if not summary_rows:
        return

    step_index = np.asarray([int(row["step"]) for row in summary_rows], dtype=int)

    def _plot_row_series(
        key: str,
        *,
        title: str,
        ylabel: str,
        filename: str,
    ) -> None:
        if key not in summary_rows[0]:
            return

        values = np.asarray([float(row[key]) for row in summary_rows], dtype=float)
        _save_line_plot(
            step_index,
            values,
            title=title,
            xlabel="paso",
            ylabel=ylabel,
            output_path=summary_dir / filename,
        )

    _plot_row_series(
        "precipitation_max_mm_dt",
        title="Precipitación máxima por paso temporal",
        ylabel="mm/dt",
        filename="precipitation_max_timeseries.png",
    )
    _plot_row_series(
        "background_fraction_of_total",
        title="Fracción de precipitación de fondo sobre el total por paso temporal",
        ylabel="fracción",
        filename="background_fraction_timeseries.png",
    )
    _plot_row_series(
        "band_reorganization_applied",
        title="Aplicación de reorganización en banda por paso temporal",
        ylabel="0/1",
        filename="band_reorganization_timeseries.png",
    )
    _plot_row_series(
        "pet_mean_mm_dt",
        title="PET media por paso temporal",
        ylabel="mm/dt",
        filename="pet_mean_timeseries.png",
    )
    _plot_row_series(
        "aet_mean_mm_dt",
        title="AET media por paso temporal",
        ylabel="mm/dt",
        filename="aet_mean_timeseries.png",
    )
    _plot_row_series(
        "soil_moisture_mean_mm",
        title="Humedad media del suelo por paso temporal",
        ylabel="mm",
        filename="soil_moisture_mean_timeseries.png",
    )
    _plot_row_series(
        "infiltration_sum_mm_dt",
        title="Infiltración total por paso temporal",
        ylabel="mm/dt",
        filename="infiltration_sum_timeseries.png",
    )
    _plot_row_series(
        "surface_runoff_sum_mm_dt",
        title="Escorrentía superficial total por paso temporal",
        ylabel="mm/dt",
        filename="surface_runoff_sum_timeseries.png",
    )
    _plot_row_series(
        "subsurface_runoff_sum_mm_dt",
        title="Escorrentía subsuperficial total por paso temporal",
        ylabel="mm/dt",
        filename="subsurface_runoff_sum_timeseries.png",
    )
    _plot_row_series(
        "shortwave_radiation_mean_w_m2",
        title="Radiación de onda corta media por paso temporal",
        ylabel="W/m2",
        filename="shortwave_radiation_mean_timeseries.png",
    )
    _plot_row_series(
        "net_radiation_mean_mj_m2_dt",
        title="Radiación neta media por paso temporal",
        ylabel="MJ/m2/dt",
        filename="net_radiation_mean_timeseries.png",
    )
    _plot_row_series(
        "channel_flow_mean_m3s",
        title="Caudal medio en el cauce por paso temporal",
        ylabel="m3/s",
        filename="channel_flow_mean_timeseries.png",
    )
    _plot_row_series(
        "outlet_discharge_m3s",
        title="Caudal en la celda de salida por paso temporal",
        ylabel="m3/s",
        filename="outlet_discharge_timeseries.png",
    )
    _plot_row_series(
        "reservoir_storage_sum_m3",
        title="Almacenamiento total en embalses por paso temporal",
        ylabel="m3",
        filename="reservoir_storage_total_timeseries.png",
    )
    _plot_row_series(
        "obs_available_count",
        title="Observaciones disponibles por paso temporal",
        ylabel="número",
        filename="observations_available_timeseries.png",
    )


def _generate_sensor_plots(
    *,
    observation_rows: list[dict[str, object]],
    output_dir: Path,
) -> None:
    """Generate one truth-vs-observed plot per sensor."""
    sensors_dir = output_dir / "sensors"
    sensors_dir.mkdir(parents=True, exist_ok=True)

    grouped: dict[tuple[int, str], list[dict[str, object]]] = {}
    for row in observation_rows:
        key = (int(row["sensor_index"]), str(row["sensor_name"]))
        grouped.setdefault(key, []).append(row)

    for (_, sensor_name), rows in sorted(grouped.items(), key=lambda item: item[0]):
        filename = _safe_filename(sensor_name)
        _save_sensor_truth_vs_observed_plot(
            rows,
            output_path=sensors_dir / f"{filename}_truth_vs_observed.png",
        )


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    run_dir = args.run_dir.resolve()
    output_dir = args.output_dir.resolve() if args.output_dir is not None else run_dir / "figures"
    output_dir.mkdir(parents=True, exist_ok=True)

    truth_ds, truth_dataset_path = _load_truth_dataset(run_dir)
    scenario_name_raw = truth_ds.attrs.get("scenario_name")
    scenario_name = str(scenario_name_raw).strip() if scenario_name_raw is not None else None

    summary_csv_path = _resolve_csv_for_scenario(
        run_dir,
        base_stem="simulation_summary",
        scenario_name=scenario_name,
    )

    observation_csv_path = _resolve_csv_for_scenario(
        run_dir,
        base_stem="simulation_observations",
        scenario_name=scenario_name,
    )

    summary_rows = _read_summary_rows(summary_csv_path)
    observation_rows = _read_observation_rows(observation_csv_path)

    print("Generando gráficas...")
    print("Tardo poco pero puedes aprovechar a tomar un café.")

    _generate_field_plots(
        truth_ds=truth_ds,
        output_dir=output_dir,
    )
    _generate_peak_step_plots(
        truth_ds=truth_ds,
        summary_rows=summary_rows,
        output_dir=output_dir,
    )
    _generate_summary_plots(
        summary_rows=summary_rows,
        output_dir=output_dir,
    )
    _generate_sensor_plots(
        observation_rows=observation_rows,
        output_dir=output_dir,
    )

    print("Generación de figuras completada correctamente.")
    print(f"Directorio de ejecución: {run_dir}")
    print(f"Dataset de verdad leído desde: {truth_dataset_path}")
    print(f"CSV de resumen leído desde: {summary_csv_path}")
    print(f"CSV de observaciones leído desde: {observation_csv_path}")
    print(f"Figuras escritas en: {output_dir}")


if __name__ == "__main__":
    main()
