from __future__ import annotations

import argparse
import csv
import pickle
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import xarray as xr


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI parser for figure generation."""
    parser = argparse.ArgumentParser(
        prog="hydro-sim-plot",
        description="Generate figures from one existing simulator run.",
    )
    parser.add_argument(
        "--run-dir",
        type=Path,
        required=True,
        help="Path to one run output directory, e.g. outputs/runs/base_run",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Optional figure output directory. Defaults to <run-dir>/figures",
    )
    return parser


def _parse_csv_float(value: str) -> float:
    """Parse one float from the project CSV format."""
    text = value.strip()

    if text == "":
        return float("nan")

    lowered = text.lower()
    if lowered in {"nan", "none"}:
        return float("nan")

    return float(text.replace(",", "."))


def _parse_csv_int(value: str) -> int:
    """Parse one integer from CSV."""
    text = value.strip()

    if text == "":
        raise ValueError("Cannot parse empty string as int")

    return int(text)


def _read_semicolon_csv(path: Path) -> list[dict[str, str]]:
    """Read one project CSV file using ';' as delimiter."""
    if not path.exists():
        raise FileNotFoundError(f"Required CSV file not found: {path}")

    with path.open("r", newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file, delimiter=";")
        return list(reader)


def _read_summary_rows(path: Path) -> list[dict[str, object]]:
    """Read and type-cast the step-summary CSV generated by the runner."""
    raw_rows = _read_semicolon_csv(path)

    parsed_rows: list[dict[str, object]] = []
    for row in raw_rows:
        parsed_rows.append(
            {
                "step": _parse_csv_int(row["step"]),
                "timestamp": row["timestamp"].strip(),
                "regime": row["regime"].strip(),
                "new_storms": _parse_csv_int(row["new_storms"]),
                "tracked_storms": _parse_csv_int(row["tracked_storms"]),
                "precipitation_sum_mm_dt": _parse_csv_float(row["precipitation_sum_mm_dt"]),
                "precipitation_max_mm_dt": _parse_csv_float(row["precipitation_max_mm_dt"]),
                "background_precipitation_sum_mm_dt": _parse_csv_float(row["background_precipitation_sum_mm_dt"]),
                "background_precipitation_max_mm_dt": _parse_csv_float(row["background_precipitation_max_mm_dt"]),
                "background_fraction_of_total": _parse_csv_float(row["background_fraction_of_total"]),
                "background_activity_factor": _parse_csv_float(row["background_activity_factor"]),
                "precipitation_spell_index": _parse_csv_float(row["precipitation_spell_index"]),
                "band_reorganization_applied": _parse_csv_int(row["band_reorganization_applied"]),
                "band_births_count": _parse_csv_int(row["band_births_count"]),
                "band_probability": _parse_csv_float(row["band_probability"]),
                "storm_mask_active_cells": _parse_csv_int(row["storm_mask_active_cells"]),
                "air_temperature_mean_c": _parse_csv_float(row["air_temperature_mean_c"]),
                "pet_mean_mm_dt": _parse_csv_float(row["pet_mean_mm_dt"]),
                "shortwave_radiation_mean_w_m2": _parse_csv_float(row["shortwave_radiation_mean_w_m2"]),
                "net_radiation_mean_mj_m2_dt": _parse_csv_float(row["net_radiation_mean_mj_m2_dt"]),
                "aet_mean_mm_dt": _parse_csv_float(row["aet_mean_mm_dt"]),
                "soil_moisture_mean_mm": _parse_csv_float(row["soil_moisture_mean_mm"]),
                "infiltration_sum_mm_dt": _parse_csv_float(row["infiltration_sum_mm_dt"]),
                "surface_runoff_sum_mm_dt": _parse_csv_float(row["surface_runoff_sum_mm_dt"]),
                "subsurface_runoff_sum_mm_dt": _parse_csv_float(row["subsurface_runoff_sum_mm_dt"]),
                "channel_flow_mean_m3s": _parse_csv_float(row["channel_flow_mean_m3s"]),
                "channel_flow_max_m3s": _parse_csv_float(row["channel_flow_max_m3s"]),
                "outlet_discharge_m3s": _parse_csv_float(row["outlet_discharge_m3s"]),
                "reservoir_inflow_sum_m3s": _parse_csv_float(row["reservoir_inflow_sum_m3s"]),
                "reservoir_release_sum_m3s": _parse_csv_float(row["reservoir_release_sum_m3s"]),
                "reservoir_spill_sum_m3s": _parse_csv_float(row["reservoir_spill_sum_m3s"]),
                "reservoir_storage_sum_m3": _parse_csv_float(row["reservoir_storage_sum_m3"]),
                "obs_available_count": _parse_csv_int(row["obs_available_count"]),
                "obs_missing_count": _parse_csv_int(row["obs_missing_count"]),
                "obs_censored_count": _parse_csv_int(row["obs_censored_count"]),
            }
        )

    return parsed_rows


def _read_observation_rows(path: Path) -> list[dict[str, object]]:
    """Read and type-cast the observation CSV generated by the runner."""
    raw_rows = _read_semicolon_csv(path)

    parsed_rows: list[dict[str, object]] = []
    for row in raw_rows:
        parsed_rows.append(
            {
                "step": _parse_csv_int(row["step"]),
                "timestamp": row["timestamp"].strip(),
                "sensor_index": _parse_csv_int(row["sensor_index"]),
                "sensor_name": row["sensor_name"].strip(),
                "sensor_type": row["sensor_type"].strip(),
                "cell_y": _parse_csv_int(row["cell_y"]),
                "cell_x": _parse_csv_int(row["cell_x"]),
                "truth_value": _parse_csv_float(row["truth_value"]),
                "observed_value": _parse_csv_float(row["observed_value"]),
                "observation_available": _parse_csv_int(row["observation_available"]),
                "quality_flag": _parse_csv_int(row["quality_flag"]),
                "quality_label": row["quality_label"].strip(),
            }
        )

    return parsed_rows


def _load_truth_dataset(run_dir: Path) -> tuple[xr.Dataset, Path]:
    """Load the truth dataset from NetCDF or pickle."""
    netcdf_path = run_dir / "simulation_truth.nc"
    pickle_path = run_dir / "simulation_truth.pkl"

    if netcdf_path.exists():
        return xr.open_dataset(netcdf_path), netcdf_path

    if pickle_path.exists():
        with pickle_path.open("rb") as file:
            ds = pickle.load(file)
        if not isinstance(ds, xr.Dataset):
            raise TypeError(f"Pickle file does not contain an xarray.Dataset: {pickle_path}")
        return ds, pickle_path

    raise FileNotFoundError(f"Truth dataset not found. Expected one of: {netcdf_path} or {pickle_path}")


def _safe_filename(text: str) -> str:
    """Convert a free-text label into a safe filename stem."""
    normalized = text.strip().lower()
    normalized = re.sub(r"\s+", "_", normalized)
    normalized = re.sub(r"[^a-z0-9_]+", "", normalized)
    return normalized or "unnamed"


def _save_field_plot(
    field: np.ndarray,
    *,
    title: str,
    output_path: Path,
    colorbar_label: str,
) -> None:
    """Save one 2D field as a PNG image."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(8, 6))
    image = plt.imshow(field, origin="lower")
    plt.title(title)
    plt.xlabel("x")
    plt.ylabel("y")
    plt.colorbar(image, label=colorbar_label)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()


def _save_line_plot(
    x: np.ndarray,
    y: np.ndarray,
    *,
    title: str,
    xlabel: str,
    ylabel: str,
    output_path: Path,
) -> None:
    """Save one simple line plot as a PNG image."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(8, 4.5))
    plt.plot(x, y)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()


def _save_sensor_truth_vs_observed_plot(
    rows: list[dict[str, object]],
    *,
    output_path: Path,
) -> None:
    """Save one sensor plot comparing truth and observed values over time."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    rows_sorted = sorted(rows, key=lambda row: int(row["step"]))

    steps = np.asarray([int(row["step"]) for row in rows_sorted], dtype=int)
    truth = np.asarray([float(row["truth_value"]) for row in rows_sorted], dtype=float)
    observed = np.asarray([float(row["observed_value"]) for row in rows_sorted], dtype=float)

    first = rows_sorted[0]
    sensor_name = str(first["sensor_name"])
    sensor_type = str(first["sensor_type"])

    plt.figure(figsize=(9, 4.5))
    plt.plot(steps, truth, label="truth")
    plt.plot(steps, observed, label="observed")
    plt.title(f"Truth vs observed - {sensor_name} ({sensor_type})")
    plt.xlabel("step")
    plt.ylabel("value")
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()


def _generate_field_plots(
    *,
    truth_ds: xr.Dataset,
    output_dir: Path,
) -> None:
    """Generate spatial field plots aggregated over the whole run."""
    fields_dir = output_dir / "fields"
    fields_dir.mkdir(parents=True, exist_ok=True)

    precipitation = np.asarray(truth_ds["precipitation"].values, dtype=float)
    background_precipitation = np.asarray(truth_ds["background_precipitation"].values, dtype=float)

    pet = np.asarray(truth_ds["pet"].values, dtype=float)
    aet = np.asarray(truth_ds["aet"].values, dtype=float)
    shortwave_radiation = np.asarray(truth_ds["shortwave_radiation"].values, dtype=float)
    net_radiation = np.asarray(truth_ds["net_radiation"].values, dtype=float)

    soil_moisture = np.asarray(truth_ds["soil_moisture"].values, dtype=float)
    infiltration = np.asarray(truth_ds["infiltration"].values, dtype=float)
    surface_runoff = np.asarray(truth_ds["surface_runoff"].values, dtype=float)
    subsurface_runoff = np.asarray(truth_ds["subsurface_runoff"].values, dtype=float)

    accumulated_precipitation = np.nansum(precipitation, axis=0)
    accumulated_background_precipitation = np.nansum(background_precipitation, axis=0)
    accumulated_pet = np.nansum(pet, axis=0)
    accumulated_aet = np.nansum(aet, axis=0)
    accumulated_infiltration = np.nansum(infiltration, axis=0)
    accumulated_surface_runoff = np.nansum(surface_runoff, axis=0)
    accumulated_subsurface_runoff = np.nansum(subsurface_runoff, axis=0)

    mean_shortwave_radiation = np.nanmean(shortwave_radiation, axis=0)
    mean_net_radiation = np.nanmean(net_radiation, axis=0)
    mean_soil_moisture = np.nanmean(soil_moisture, axis=0)
    final_soil_moisture = soil_moisture[-1] if soil_moisture.shape[0] > 0 else np.zeros(soil_moisture.shape[1:], dtype=float)

    _save_field_plot(
        accumulated_precipitation,
        title="Accumulated precipitation",
        output_path=fields_dir / "accumulated_precipitation.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_background_precipitation,
        title="Accumulated background precipitation",
        output_path=fields_dir / "accumulated_background_precipitation.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_pet,
        title="Accumulated PET",
        output_path=fields_dir / "accumulated_pet.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_aet,
        title="Accumulated AET",
        output_path=fields_dir / "accumulated_aet.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_infiltration,
        title="Accumulated infiltration",
        output_path=fields_dir / "accumulated_infiltration.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_surface_runoff,
        title="Accumulated surface runoff",
        output_path=fields_dir / "accumulated_surface_runoff.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_subsurface_runoff,
        title="Accumulated subsurface runoff",
        output_path=fields_dir / "accumulated_subsurface_runoff.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        mean_soil_moisture,
        title="Mean soil moisture",
        output_path=fields_dir / "mean_soil_moisture.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        final_soil_moisture,
        title="Final soil moisture",
        output_path=fields_dir / "final_soil_moisture.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        mean_shortwave_radiation,
        title="Mean shortwave radiation",
        output_path=fields_dir / "mean_shortwave_radiation.png",
        colorbar_label="W/m2",
    )
    _save_field_plot(
        mean_net_radiation,
        title="Mean net radiation",
        output_path=fields_dir / "mean_net_radiation.png",
        colorbar_label="MJ/m2/dt",
    )


def _generate_peak_step_plots(
    *,
    truth_ds: xr.Dataset,
    summary_rows: list[dict[str, object]],
    output_dir: Path,
) -> None:
    """Generate peak-step and special-step spatial plots."""
    fields_dir = output_dir / "fields"
    fields_dir.mkdir(parents=True, exist_ok=True)

    precipitation = np.asarray(truth_ds["precipitation"].values, dtype=float)
    storm_mask = np.asarray(truth_ds["storm_mask"].values, dtype=bool)
    infiltration = np.asarray(truth_ds["infiltration"].values, dtype=float)
    surface_runoff = np.asarray(truth_ds["surface_runoff"].values, dtype=float)
    soil_moisture = np.asarray(truth_ds["soil_moisture"].values, dtype=float)
    channel_flow = np.asarray(truth_ds["channel_flow"].values, dtype=float)

    if precipitation.shape[0] > 0 and np.isfinite(precipitation).any():
        peak_precip_step = int(np.nanargmax(np.nanmax(precipitation, axis=(1, 2))))

        _save_field_plot(
            precipitation[peak_precip_step],
            title=f"Precipitation at peak step {peak_precip_step}",
            output_path=fields_dir / "step_peak_precipitation.png",
            colorbar_label="mm/dt",
        )
        _save_field_plot(
            storm_mask[peak_precip_step].astype(float),
            title=f"Storm mask at peak precipitation step {peak_precip_step}",
            output_path=fields_dir / "step_peak_storm_mask.png",
            colorbar_label="1",
        )

    if surface_runoff.shape[0] > 0 and np.isfinite(surface_runoff).any():
        peak_runoff_step = int(np.nanargmax(np.nanmax(surface_runoff, axis=(1, 2))))

        _save_field_plot(
            surface_runoff[peak_runoff_step],
            title=f"Surface runoff at peak step {peak_runoff_step}",
            output_path=fields_dir / "step_peak_surface_runoff.png",
            colorbar_label="mm/dt",
        )
        _save_field_plot(
            infiltration[peak_runoff_step],
            title=f"Infiltration at peak runoff step {peak_runoff_step}",
            output_path=fields_dir / "step_peak_infiltration.png",
            colorbar_label="mm/dt",
        )
        _save_field_plot(
            soil_moisture[peak_runoff_step],
            title=f"Soil moisture at peak runoff step {peak_runoff_step}",
            output_path=fields_dir / "step_peak_runoff_soil_moisture.png",
            colorbar_label="mm",
        )
        _save_field_plot(
            channel_flow[peak_runoff_step],
            title=f"Channel flow at peak runoff step {peak_runoff_step}",
            output_path=fields_dir / "step_peak_channel_flow.png",
            colorbar_label="m3/s",
        )

    if summary_rows and "band_reorganization_applied" in summary_rows[0]:
        band_steps = [int(row["step"]) for row in summary_rows if int(row["band_reorganization_applied"]) == 1]

        if band_steps:
            first_band_step = band_steps[0]

            _save_field_plot(
                precipitation[first_band_step],
                title=f"Precipitation at first band step {first_band_step}",
                output_path=fields_dir / "step_first_band_precipitation.png",
                colorbar_label="mm/dt",
            )
            _save_field_plot(
                storm_mask[first_band_step].astype(float),
                title=f"Storm mask at first band step {first_band_step}",
                output_path=fields_dir / "step_first_band_storm_mask.png",
                colorbar_label="1",
            )


def _generate_summary_plots(
    *,
    summary_rows: list[dict[str, object]],
    output_dir: Path,
) -> None:
    """Generate time-series plots from the step summary CSV."""
    summary_dir = output_dir / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)

    if not summary_rows:
        return

    step_index = np.asarray([int(row["step"]) for row in summary_rows], dtype=int)

    def _plot_row_series(
        key: str,
        *,
        title: str,
        ylabel: str,
        filename: str,
    ) -> None:
        if key not in summary_rows[0]:
            return

        values = np.asarray([float(row[key]) for row in summary_rows], dtype=float)
        _save_line_plot(
            step_index,
            values,
            title=title,
            xlabel="step",
            ylabel=ylabel,
            output_path=summary_dir / filename,
        )

    _plot_row_series(
        "precipitation_max_mm_dt",
        title="Maximum precipitation per step",
        ylabel="mm/dt",
        filename="precipitation_max_timeseries.png",
    )
    _plot_row_series(
        "background_fraction_of_total",
        title="Background fraction of total precipitation",
        ylabel="fraction",
        filename="background_fraction_timeseries.png",
    )
    _plot_row_series(
        "band_reorganization_applied",
        title="Band reorganization applied",
        ylabel="0/1",
        filename="band_reorganization_timeseries.png",
    )
    _plot_row_series(
        "pet_mean_mm_dt",
        title="Mean PET per step",
        ylabel="mm/dt",
        filename="pet_mean_timeseries.png",
    )
    _plot_row_series(
        "aet_mean_mm_dt",
        title="Mean AET per step",
        ylabel="mm/dt",
        filename="aet_mean_timeseries.png",
    )
    _plot_row_series(
        "soil_moisture_mean_mm",
        title="Mean soil moisture per step",
        ylabel="mm",
        filename="soil_moisture_mean_timeseries.png",
    )
    _plot_row_series(
        "infiltration_sum_mm_dt",
        title="Total infiltration per step",
        ylabel="mm/dt",
        filename="infiltration_sum_timeseries.png",
    )
    _plot_row_series(
        "surface_runoff_sum_mm_dt",
        title="Total surface runoff per step",
        ylabel="mm/dt",
        filename="surface_runoff_sum_timeseries.png",
    )
    _plot_row_series(
        "subsurface_runoff_sum_mm_dt",
        title="Total subsurface runoff per step",
        ylabel="mm/dt",
        filename="subsurface_runoff_sum_timeseries.png",
    )
    _plot_row_series(
        "shortwave_radiation_mean_w_m2",
        title="Mean shortwave radiation per step",
        ylabel="W/m2",
        filename="shortwave_radiation_mean_timeseries.png",
    )
    _plot_row_series(
        "net_radiation_mean_mj_m2_dt",
        title="Mean net radiation per step",
        ylabel="MJ/m2/dt",
        filename="net_radiation_mean_timeseries.png",
    )
    _plot_row_series(
        "channel_flow_mean_m3s",
        title="Mean channel flow per step",
        ylabel="m3/s",
        filename="channel_flow_mean_timeseries.png",
    )
    _plot_row_series(
        "outlet_discharge_m3s",
        title="Outlet discharge per step",
        ylabel="m3/s",
        filename="outlet_discharge_timeseries.png",
    )
    _plot_row_series(
        "reservoir_storage_sum_m3",
        title="Total reservoir storage over time",
        ylabel="m3",
        filename="reservoir_storage_total_timeseries.png",
    )
    _plot_row_series(
        "obs_available_count",
        title="Available observations per step",
        ylabel="count",
        filename="observations_available_timeseries.png",
    )


def _generate_sensor_plots(
    *,
    observation_rows: list[dict[str, object]],
    output_dir: Path,
) -> None:
    """Generate one truth-vs-observed plot per sensor."""
    sensors_dir = output_dir / "sensors"
    sensors_dir.mkdir(parents=True, exist_ok=True)

    grouped: dict[tuple[int, str], list[dict[str, object]]] = {}
    for row in observation_rows:
        key = (int(row["sensor_index"]), str(row["sensor_name"]))
        grouped.setdefault(key, []).append(row)

    for (_, sensor_name), rows in sorted(grouped.items(), key=lambda item: item[0]):
        filename = _safe_filename(sensor_name)
        _save_sensor_truth_vs_observed_plot(
            rows,
            output_path=sensors_dir / f"{filename}_truth_vs_observed.png",
        )


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    run_dir = args.run_dir.resolve()
    output_dir = args.output_dir.resolve() if args.output_dir is not None else run_dir / "figures"
    output_dir.mkdir(parents=True, exist_ok=True)

    truth_ds, truth_dataset_path = _load_truth_dataset(run_dir)
    summary_csv_path = run_dir / "simulation_summary.csv"
    observation_csv_path = run_dir / "simulation_observations.csv"

    summary_rows = _read_summary_rows(summary_csv_path)
    observation_rows = _read_observation_rows(observation_csv_path)

    _generate_field_plots(
        truth_ds=truth_ds,
        output_dir=output_dir,
    )
    _generate_peak_step_plots(
        truth_ds=truth_ds,
        summary_rows=summary_rows,
        output_dir=output_dir,
    )
    _generate_summary_plots(
        summary_rows=summary_rows,
        output_dir=output_dir,
    )
    _generate_sensor_plots(
        observation_rows=observation_rows,
        output_dir=output_dir,
    )

    print("Figure generation completed successfully.")
    print(f"Run directory: {run_dir}")
    print(f"Truth dataset read from: {truth_dataset_path}")
    print(f"Summary CSV read from: {summary_csv_path}")
    print(f"Observation CSV read from: {observation_csv_path}")
    print(f"Figures written to: {output_dir}")


if __name__ == "__main__":
    main()
