from __future__ import annotations

import argparse
import csv
import pickle
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import xarray as xr


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI parser for figure generation."""
    parser = argparse.ArgumentParser(
        prog="hydro-sim-plot",
        description="Generate figures from one existing simulator run.",
    )
    parser.add_argument(
        "--run-dir",
        type=Path,
        required=True,
        help="Path to one run output directory, e.g. outputs/runs/base_run",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Optional figure output directory. Defaults to <run-dir>/figures",
    )
    return parser


def _parse_csv_float(value: str) -> float:
    """Parse one float from the project CSV format."""
    text = value.strip()

    if text == "":
        return float("nan")

    lowered = text.lower()
    if lowered in {"nan", "none"}:
        return float("nan")

    return float(text.replace(",", "."))


def _parse_csv_int(value: str) -> int:
    """Parse one integer from CSV."""
    text = value.strip()

    if text == "":
        raise ValueError("Cannot parse empty string as int")

    return int(text)


def _read_semicolon_csv(path: Path) -> list[dict[str, str]]:
    """Read one project CSV file using ';' as delimiter."""
    if not path.exists():
        raise FileNotFoundError(f"Required CSV file not found: {path}")

    with path.open("r", newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file, delimiter=";")
        return list(reader)


def _read_summary_rows(path: Path) -> list[dict[str, object]]:
    """Read and type-cast the step-summary CSV generated by the runner."""
    raw_rows = _read_semicolon_csv(path)

    parsed_rows: list[dict[str, object]] = []
    for row in raw_rows:
        parsed_rows.append(
            {
                "step": _parse_csv_int(row["step"]),
                "timestamp": row["timestamp"].strip(),
                "precipitation_sum_mm_dt": _parse_csv_float(row["precipitation_sum_mm_dt"]),
                "precipitation_max_mm_dt": _parse_csv_float(row["precipitation_max_mm_dt"]),
                "pet_mean_mm_dt": _parse_csv_float(row["pet_mean_mm_dt"]),
                "aet_mean_mm_dt": _parse_csv_float(row["aet_mean_mm_dt"]),
                "soil_moisture_mean_mm": _parse_csv_float(row["soil_moisture_mean_mm"]),
                "surface_runoff_sum_mm_dt": _parse_csv_float(row["surface_runoff_sum_mm_dt"]),
                "subsurface_runoff_sum_mm_dt": _parse_csv_float(row["subsurface_runoff_sum_mm_dt"]),
                "channel_flow_mean_m3s": _parse_csv_float(row["channel_flow_mean_m3s"]),
                "outlet_discharge_m3s": _parse_csv_float(row["outlet_discharge_m3s"]),
                "reservoir_storage_sum_m3": _parse_csv_float(row["reservoir_storage_sum_m3"]),
                "obs_available_count": _parse_csv_int(row["obs_available_count"]),
                "obs_missing_count": _parse_csv_int(row["obs_missing_count"]),
                "obs_censored_count": _parse_csv_int(row["obs_censored_count"]),
            }
        )

    return parsed_rows


def _read_observation_rows(path: Path) -> list[dict[str, object]]:
    """Read and type-cast the observation CSV generated by the runner."""
    raw_rows = _read_semicolon_csv(path)

    parsed_rows: list[dict[str, object]] = []
    for row in raw_rows:
        parsed_rows.append(
            {
                "step": _parse_csv_int(row["step"]),
                "timestamp": row["timestamp"].strip(),
                "sensor_index": _parse_csv_int(row["sensor_index"]),
                "sensor_name": row["sensor_name"].strip(),
                "sensor_type": row["sensor_type"].strip(),
                "cell_y": _parse_csv_int(row["cell_y"]),
                "cell_x": _parse_csv_int(row["cell_x"]),
                "truth_value": _parse_csv_float(row["truth_value"]),
                "observed_value": _parse_csv_float(row["observed_value"]),
                "observation_available": _parse_csv_int(row["observation_available"]),
                "quality_flag": _parse_csv_int(row["quality_flag"]),
                "quality_label": row["quality_label"].strip(),
            }
        )

    return parsed_rows


def _load_truth_dataset(run_dir: Path) -> tuple[xr.Dataset, Path]:
    """Load the truth dataset from NetCDF or pickle."""
    netcdf_path = run_dir / "simulation_truth.nc"
    pickle_path = run_dir / "simulation_truth.pkl"

    if netcdf_path.exists():
        return xr.open_dataset(netcdf_path), netcdf_path

    if pickle_path.exists():
        with pickle_path.open("rb") as file:
            ds = pickle.load(file)
        if not isinstance(ds, xr.Dataset):
            raise TypeError(f"Pickle file does not contain an xarray.Dataset: {pickle_path}")
        return ds, pickle_path

    raise FileNotFoundError(f"Truth dataset not found. Expected one of: {netcdf_path} or {pickle_path}")


def _safe_filename(text: str) -> str:
    """Convert a free-text label into a safe filename stem."""
    normalized = text.strip().lower()
    normalized = re.sub(r"\s+", "_", normalized)
    normalized = re.sub(r"[^a-z0-9_]+", "", normalized)
    return normalized or "unnamed"


def _save_field_plot(
    field: np.ndarray,
    *,
    title: str,
    output_path: Path,
    colorbar_label: str,
) -> None:
    """Save one 2D field as a PNG image."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(8, 6))
    image = plt.imshow(field, origin="lower")
    plt.title(title)
    plt.xlabel("x")
    plt.ylabel("y")
    plt.colorbar(image, label=colorbar_label)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()


def _save_line_plot(
    x: np.ndarray,
    y: np.ndarray,
    *,
    title: str,
    xlabel: str,
    ylabel: str,
    output_path: Path,
) -> None:
    """Save one simple line plot as a PNG image."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(8, 4.5))
    plt.plot(x, y)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()


def _save_sensor_truth_vs_observed_plot(
    rows: list[dict[str, object]],
    *,
    output_path: Path,
) -> None:
    """Save one sensor plot comparing truth and observed values over time."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    rows_sorted = sorted(rows, key=lambda row: int(row["step"]))

    steps = np.asarray([int(row["step"]) for row in rows_sorted], dtype=int)
    truth = np.asarray([float(row["truth_value"]) for row in rows_sorted], dtype=float)
    observed = np.asarray([float(row["observed_value"]) for row in rows_sorted], dtype=float)

    first = rows_sorted[0]
    sensor_name = str(first["sensor_name"])
    sensor_type = str(first["sensor_type"])

    plt.figure(figsize=(9, 4.5))
    plt.plot(steps, truth, label="truth")
    plt.plot(steps, observed, label="observed")
    plt.title(f"Truth vs observed - {sensor_name} ({sensor_type})")
    plt.xlabel("step")
    plt.ylabel("value")
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()


def _generate_field_plots(
    *,
    truth_ds: xr.Dataset,
    output_dir: Path,
) -> None:
    """Generate spatial field plots aggregated over the whole run."""
    fields_dir = output_dir / "fields"
    fields_dir.mkdir(parents=True, exist_ok=True)

    precipitation = np.asarray(truth_ds["precipitation"].values, dtype=float)
    pet = np.asarray(truth_ds["pet"].values, dtype=float)
    aet = np.asarray(truth_ds["aet"].values, dtype=float)
    surface_runoff = np.asarray(truth_ds["surface_runoff"].values, dtype=float)
    soil_moisture = np.asarray(truth_ds["soil_moisture"].values, dtype=float)

    accumulated_precipitation = np.nansum(precipitation, axis=0)
    accumulated_pet = np.nansum(pet, axis=0)
    accumulated_aet = np.nansum(aet, axis=0)
    accumulated_surface_runoff = np.nansum(surface_runoff, axis=0)
    final_soil_moisture = soil_moisture[-1] if soil_moisture.shape[0] > 0 else np.zeros(soil_moisture.shape[1:], dtype=float)

    _save_field_plot(
        accumulated_precipitation,
        title="Accumulated precipitation",
        output_path=fields_dir / "accumulated_precipitation.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_pet,
        title="Accumulated PET",
        output_path=fields_dir / "accumulated_pet.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_aet,
        title="Accumulated AET",
        output_path=fields_dir / "accumulated_aet.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        accumulated_surface_runoff,
        title="Accumulated surface runoff",
        output_path=fields_dir / "accumulated_surface_runoff.png",
        colorbar_label="mm",
    )
    _save_field_plot(
        final_soil_moisture,
        title="Final soil moisture",
        output_path=fields_dir / "final_soil_moisture.png",
        colorbar_label="mm",
    )


def _generate_summary_plots(
    *,
    summary_rows: list[dict[str, object]],
    output_dir: Path,
) -> None:
    """Generate time-series plots from the step summary CSV."""
    summary_dir = output_dir / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)

    if not summary_rows:
        return

    step_index = np.asarray([int(row["step"]) for row in summary_rows], dtype=int)

    def _series(key: str) -> np.ndarray:
        return np.asarray([float(row[key]) for row in summary_rows], dtype=float)

    _save_line_plot(
        step_index,
        _series("outlet_discharge_m3s"),
        title="Outlet discharge over time",
        xlabel="step",
        ylabel="m3/s",
        output_path=summary_dir / "outlet_discharge_timeseries.png",
    )
    _save_line_plot(
        step_index,
        _series("channel_flow_mean_m3s"),
        title="Mean channel flow over time",
        xlabel="step",
        ylabel="m3/s",
        output_path=summary_dir / "channel_flow_mean_timeseries.png",
    )
    _save_line_plot(
        step_index,
        _series("reservoir_storage_sum_m3"),
        title="Total reservoir storage over time",
        xlabel="step",
        ylabel="m3",
        output_path=summary_dir / "reservoir_storage_total_timeseries.png",
    )
    _save_line_plot(
        step_index,
        _series("precipitation_max_mm_dt"),
        title="Maximum precipitation per step",
        xlabel="step",
        ylabel="mm/dt",
        output_path=summary_dir / "precipitation_max_timeseries.png",
    )
    _save_line_plot(
        step_index,
        _series("obs_available_count"),
        title="Available observations per step",
        xlabel="step",
        ylabel="count",
        output_path=summary_dir / "observations_available_timeseries.png",
    )


def _generate_sensor_plots(
    *,
    observation_rows: list[dict[str, object]],
    output_dir: Path,
) -> None:
    """Generate one truth-vs-observed plot per sensor."""
    sensors_dir = output_dir / "sensors"
    sensors_dir.mkdir(parents=True, exist_ok=True)

    grouped: dict[tuple[int, str], list[dict[str, object]]] = {}
    for row in observation_rows:
        key = (int(row["sensor_index"]), str(row["sensor_name"]))
        grouped.setdefault(key, []).append(row)

    for (_, sensor_name), rows in sorted(grouped.items(), key=lambda item: item[0]):
        filename = _safe_filename(sensor_name)
        _save_sensor_truth_vs_observed_plot(
            rows,
            output_path=sensors_dir / f"{filename}_truth_vs_observed.png",
        )


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    run_dir = args.run_dir.resolve()
    output_dir = args.output_dir.resolve() if args.output_dir is not None else run_dir / "figures"
    output_dir.mkdir(parents=True, exist_ok=True)

    truth_ds, truth_dataset_path = _load_truth_dataset(run_dir)
    summary_csv_path = run_dir / "simulation_summary.csv"
    observation_csv_path = run_dir / "simulation_observations.csv"

    summary_rows = _read_summary_rows(summary_csv_path)
    observation_rows = _read_observation_rows(observation_csv_path)

    _generate_field_plots(
        truth_ds=truth_ds,
        output_dir=output_dir,
    )
    _generate_summary_plots(
        summary_rows=summary_rows,
        output_dir=output_dir,
    )
    _generate_sensor_plots(
        observation_rows=observation_rows,
        output_dir=output_dir,
    )

    print("Figure generation completed successfully.")
    print(f"Run directory: {run_dir}")
    print(f"Truth dataset read from: {truth_dataset_path}")
    print(f"Summary CSV read from: {summary_csv_path}")
    print(f"Observation CSV read from: {observation_csv_path}")
    print(f"Figures written to: {output_dir}")


if __name__ == "__main__":
    main()
