from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI parser for validation."""
    parser = argparse.ArgumentParser(
        prog="hydro-sim-validate",
        description="Valida una ejecución del simulador usando los CSV generados.",
    )
    parser.add_argument(
        "--run-dir",
        type=Path,
        required=True,
        help="Ruta al directorio de salida de una ejecución, por ejemplo outputs/runs/base_run",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directorio opcional para las salidas de validación. Por defecto: <run-dir>/validation",
    )
    return parser


def _parse_csv_float(value: str) -> float:
    """Parse one float from the project CSV format.

    Supported inputs
    ----------------
    - comma decimal separator, e.g. '1,250000'
    - standard decimal separator, e.g. '1.250000'
    - 'nan' / empty values
    """
    text = value.strip()

    if text == "":
        return float("nan")

    lowered = text.lower()
    if lowered in {"nan", "none"}:
        return float("nan")

    return float(text.replace(",", "."))


def _parse_csv_int(value: str) -> int:
    """Parse one integer from CSV."""
    text = value.strip()

    if text == "":
        raise ValueError("No se puede interpretar una cadena vacía como entero")

    return int(text)


def _read_semicolon_csv(path: Path) -> list[dict[str, str]]:
    """Read one project CSV file using ';' as delimiter."""
    if not path.exists():
        raise FileNotFoundError(f"No se encontró el archivo CSV requerido: {path}")

    with path.open("r", newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file, delimiter=";")
        return list(reader)


def _write_csv(
    *,
    rows: list[dict[str, object]],
    output_path: Path,
) -> None:
    """Write one CSV using the same spreadsheet-friendly formatting as run.py."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if not rows:
        return

    fieldnames = list(rows[0].keys())

    def _format_csv_value(value: object) -> object:
        if isinstance(value, float):
            if np.isnan(value):
                return "nan"
            return f"{value:.6f}".replace(".", ",")
        return value

    formatted_rows = [{key: _format_csv_value(value) for key, value in row.items()} for row in rows]

    with output_path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames, delimiter=";")
        writer.writeheader()
        writer.writerows(formatted_rows)


def _read_observation_rows(path: Path) -> list[dict[str, object]]:
    """Read and type-cast the observation CSV generated by the runner."""
    raw_rows = _read_semicolon_csv(path)

    parsed_rows: list[dict[str, object]] = []
    for row in raw_rows:
        parsed_rows.append(
            {
                "step": _parse_csv_int(row["step"]),
                "timestamp": row["timestamp"].strip(),
                "sensor_index": _parse_csv_int(row["sensor_index"]),
                "sensor_name": row["sensor_name"].strip(),
                "sensor_type": row["sensor_type"].strip(),
                "cell_y": _parse_csv_int(row["cell_y"]),
                "cell_x": _parse_csv_int(row["cell_x"]),
                "truth_value": _parse_csv_float(row["truth_value"]),
                "observed_value": _parse_csv_float(row["observed_value"]),
                "observation_available": _parse_csv_int(row["observation_available"]),
                "quality_flag": _parse_csv_int(row["quality_flag"]),
                "quality_label": row["quality_label"].strip(),
            }
        )

    return parsed_rows


def _read_summary_rows(path: Path) -> list[dict[str, object]]:
    """Read and type-cast the step-summary CSV generated by the runner."""
    raw_rows = _read_semicolon_csv(path)

    parsed_rows: list[dict[str, object]] = []
    for row in raw_rows:
        parsed_rows.append(
            {
                "step": _parse_csv_int(row["step"]),
                "timestamp": row["timestamp"].strip(),
                "regime": row["regime"].strip(),
                "new_storms": _parse_csv_int(row["new_storms"]),
                "tracked_storms": _parse_csv_int(row["tracked_storms"]),
                "precipitation_sum_mm_dt": _parse_csv_float(row["precipitation_sum_mm_dt"]),
                "precipitation_max_mm_dt": _parse_csv_float(row["precipitation_max_mm_dt"]),
                "background_precipitation_sum_mm_dt": _parse_csv_float(row["background_precipitation_sum_mm_dt"]),
                "background_precipitation_max_mm_dt": _parse_csv_float(row["background_precipitation_max_mm_dt"]),
                "background_fraction_of_total": _parse_csv_float(row["background_fraction_of_total"]),
                "background_activity_factor": _parse_csv_float(row["background_activity_factor"]),
                "precipitation_spell_index": _parse_csv_float(row["precipitation_spell_index"]),
                "band_reorganization_applied": _parse_csv_int(row["band_reorganization_applied"]),
                "band_births_count": _parse_csv_int(row["band_births_count"]),
                "band_probability": _parse_csv_float(row["band_probability"]),
                "storm_mask_active_cells": _parse_csv_int(row["storm_mask_active_cells"]),
                "air_temperature_min_c": _parse_csv_float(row["air_temperature_min_c"]),
                "air_temperature_mean_c": _parse_csv_float(row["air_temperature_mean_c"]),
                "air_temperature_max_c": _parse_csv_float(row["air_temperature_max_c"]),
                "air_temperature_range_c": _parse_csv_float(row["air_temperature_range_c"]),
                "pet_mean_mm_dt": _parse_csv_float(row["pet_mean_mm_dt"]),
                "shortwave_radiation_mean_w_m2": _parse_csv_float(row["shortwave_radiation_mean_w_m2"]),
                "net_radiation_mean_mj_m2_dt": _parse_csv_float(row["net_radiation_mean_mj_m2_dt"]),
                "aet_mean_mm_dt": _parse_csv_float(row["aet_mean_mm_dt"]),
                "soil_moisture_mean_mm": _parse_csv_float(row["soil_moisture_mean_mm"]),
                "infiltration_sum_mm_dt": _parse_csv_float(row["infiltration_sum_mm_dt"]),
                "surface_runoff_sum_mm_dt": _parse_csv_float(row["surface_runoff_sum_mm_dt"]),
                "subsurface_runoff_sum_mm_dt": _parse_csv_float(row["subsurface_runoff_sum_mm_dt"]),
                "channel_flow_mean_m3s": _parse_csv_float(row["channel_flow_mean_m3s"]),
                "channel_flow_max_m3s": _parse_csv_float(row["channel_flow_max_m3s"]),
                "outlet_discharge_m3s": _parse_csv_float(row["outlet_discharge_m3s"]),
                "reservoir_inflow_sum_m3s": _parse_csv_float(row["reservoir_inflow_sum_m3s"]),
                "reservoir_release_sum_m3s": _parse_csv_float(row["reservoir_release_sum_m3s"]),
                "reservoir_spill_sum_m3s": _parse_csv_float(row["reservoir_spill_sum_m3s"]),
                "reservoir_storage_sum_m3": _parse_csv_float(row["reservoir_storage_sum_m3"]),
                "obs_available_count": _parse_csv_int(row["obs_available_count"]),
                "obs_missing_count": _parse_csv_int(row["obs_missing_count"]),
                "obs_censored_count": _parse_csv_int(row["obs_censored_count"]),
            }
        )

    return parsed_rows


def _csv_scenario_suffix(path: Path, *, base_stem: str) -> str | None:
    """Return the scenario suffix encoded in one generated CSV filename."""
    if path.stem == base_stem:
        return None

    prefix = f"{base_stem}_"
    if not path.stem.startswith(prefix):
        raise ValueError(f"El archivo {path} no coincide con el prefijo esperado {prefix!r}")

    suffix = path.stem[len(prefix) :]
    if not suffix:
        raise ValueError(f"El archivo {path} no contiene sufijo de escenario válido")

    return suffix


def _collect_input_csv_candidates(run_dir: Path, *, base_stem: str) -> dict[str | None, Path]:
    """Collect canonical and scenario-suffixed English CSV candidates."""
    candidates: list[Path] = []

    canonical_path = run_dir / f"{base_stem}.csv"
    if canonical_path.exists():
        candidates.append(canonical_path)

    candidates.extend(sorted(path for path in run_dir.glob(f"{base_stem}_*.csv") if path.is_file() and not path.stem.endswith("_es")))

    resolved: dict[str | None, Path] = {}
    for path in candidates:
        suffix = _csv_scenario_suffix(path, base_stem=base_stem)

        if suffix in resolved:
            raise RuntimeError(f"Hay varios CSV para el mismo escenario {suffix!r}: {resolved[suffix]} y {path}")

        resolved[suffix] = path

    return resolved


def _format_suffix_for_message(suffix: str | None) -> str:
    """Format one scenario suffix for user-facing messages."""
    return "sin sufijo" if suffix is None else suffix


SENSOR_TYPE_LABELS_ES: dict[str, str] = {
    "precipitation": "precipitacion",
    "discharge": "caudal",
    "reservoir_storage": "almacenamiento en embalse",
}


def _format_sensor_type_for_output(sensor_type: str) -> str:
    """Return a Spanish label for one sensor type in validation outputs."""
    normalized = sensor_type.strip().lower()
    return SENSOR_TYPE_LABELS_ES.get(normalized, sensor_type)


def _resolve_validation_csv_paths(run_dir: Path) -> tuple[Path, Path]:
    """Resolve the matching English summary and observation CSV files for validation."""
    summary_candidates = _collect_input_csv_candidates(
        run_dir,
        base_stem="simulation_summary",
    )
    observation_candidates = _collect_input_csv_candidates(
        run_dir,
        base_stem="simulation_observations",
    )

    common_suffixes = sorted(
        set(summary_candidates) & set(observation_candidates),
        key=lambda suffix: "" if suffix is None else suffix,
    )

    if not common_suffixes:
        raise FileNotFoundError(
            "No se ha encontrado una pareja válida de CSV de entrada en "
            f"{run_dir}. Se esperaba una pareja con el mismo sufijo de escenario: "
            "simulation_summary_<escenario>.csv y "
            "simulation_observations_<escenario>.csv, o los nombres antiguos sin sufijo."
        )

    if len(common_suffixes) > 1:
        suffixes_text = ", ".join(_format_suffix_for_message(suffix) for suffix in common_suffixes)
        raise RuntimeError(
            "Se han encontrado varias parejas de CSV de validación. "
            "Usa un directorio de ejecución con un único escenario o separa los resultados. "
            f"Sufijos encontrados: {suffixes_text}"
        )

    scenario_suffix = common_suffixes[0]
    return observation_candidates[scenario_suffix], summary_candidates[scenario_suffix]


def _safe_mean(values: np.ndarray) -> float:
    """Return nanmean or NaN if the array is empty."""
    if values.size == 0:
        return float("nan")
    return float(np.nanmean(values))


def _safe_sum(values: np.ndarray) -> float:
    """Return nansum or NaN if the array is empty."""
    if values.size == 0:
        return float("nan")
    return float(np.nansum(values))


def _safe_max(values: np.ndarray) -> float:
    """Return nanmax or NaN if the array is empty."""
    if values.size == 0:
        return float("nan")
    if np.all(np.isnan(values)):
        return float("nan")
    return float(np.nanmax(values))


def _compute_error_metrics(
    *,
    truth_values: np.ndarray,
    observed_values: np.ndarray,
) -> dict[str, float]:
    """Compute basic error metrics for one validation group.

    Bias: mean of observed - truth
        - Bias tells you if the sensor tends to overestimate or underestimate.
    MAE: mean absolute error
        - MAE gives you a medium error in physical units
    RMSE: root mean square error
        - RMSE penalizes large errors more.
    """
    if truth_values.size == 0 or observed_values.size == 0:
        return {
            "bias": float("nan"),
            "mae": float("nan"),
            "rmse": float("nan"),
        }

    errors = observed_values - truth_values

    return {
        "bias": float(np.mean(errors)),
        "mae": float(np.mean(np.abs(errors))),
        "rmse": float(np.sqrt(np.mean(errors**2))),
    }


def _summarize_observation_group(
    *,
    rows: list[dict[str, object]],
    label_fields: dict[str, object],
) -> dict[str, object]:
    """Summarize one group of observation rows."""
    n_total = len(rows)
    n_available = sum(int(row["observation_available"]) for row in rows)
    n_missing = n_total - n_available
    n_censored = sum(int(row["quality_flag"]) == 2 for row in rows)

    valid_rows = [
        row
        for row in rows
        if int(row["observation_available"]) == 1
        and np.isfinite(float(row["truth_value"]))
        and np.isfinite(float(row["observed_value"]))
    ]

    truth_values = np.asarray([float(row["truth_value"]) for row in valid_rows], dtype=float)
    observed_values = np.asarray([float(row["observed_value"]) for row in valid_rows], dtype=float)

    metrics = _compute_error_metrics(
        truth_values=truth_values,
        observed_values=observed_values,
    )

    mean_truth = _safe_mean(truth_values)
    mae_relative_to_mean_truth = (
        float(metrics["mae"] / mean_truth)
        if np.isfinite(mean_truth) and mean_truth > 0.0 and np.isfinite(metrics["mae"])
        else float("nan")
    )
    rmse_relative_to_mean_truth = (
        float(metrics["rmse"] / mean_truth)
        if np.isfinite(mean_truth) and mean_truth > 0.0 and np.isfinite(metrics["rmse"])
        else float("nan")
    )
    bias_relative_to_mean_truth = (
        float(metrics["bias"] / mean_truth)
        if np.isfinite(mean_truth) and mean_truth > 0.0 and np.isfinite(metrics["bias"])
        else float("nan")
    )

    summary = {
        **label_fields,
        "numero_observaciones_totales": n_total,
        "numero_observaciones_disponibles": n_available,
        "numero_observaciones_faltantes": n_missing,
        "numero_observaciones_censuradas": n_censored,
        "tasa_faltantes": (0.0 if n_total == 0 else n_missing / n_total),
        "tasa_censuradas_total": (0.0 if n_total == 0 else n_censored / n_total),
        "tasa_censuradas_sobre_disponibles": (0.0 if n_available == 0 else n_censored / n_available),
        "verdad_media": mean_truth,
        "sesgo": metrics["bias"],
        "error_absoluto_medio": metrics["mae"],
        "raiz_error_cuadratico_medio": metrics["rmse"],
        "error_absoluto_medio_relativo": mae_relative_to_mean_truth,
        "raiz_error_cuadratico_medio_relativo": rmse_relative_to_mean_truth,
        "sesgo_relativo": bias_relative_to_mean_truth,
        "numero_observaciones_validas_para_metricas": len(valid_rows),
    }

    return summary


def _build_observation_validation_by_sensor(
    observation_rows: list[dict[str, object]],
) -> list[dict[str, object]]:
    """Build one validation row per sensor."""
    grouped: dict[tuple[int, str], list[dict[str, object]]] = {}

    for row in observation_rows:
        key = (int(row["sensor_index"]), str(row["sensor_name"]))
        grouped.setdefault(key, []).append(row)

    output_rows: list[dict[str, object]] = []
    for (_, _), rows in sorted(grouped.items(), key=lambda item: item[0]):
        first = rows[0]
        output_rows.append(
            _summarize_observation_group(
                rows=rows,
                label_fields={
                    "indice_sensor": int(first["sensor_index"]),
                    "nombre_sensor": str(first["sensor_name"]),
                    "tipo_sensor": _format_sensor_type_for_output(str(first["sensor_type"])),
                    "celda_y": int(first["cell_y"]),
                    "celda_x": int(first["cell_x"]),
                },
            )
        )

    return output_rows


def _build_observation_validation_by_type(
    observation_rows: list[dict[str, object]],
) -> list[dict[str, object]]:
    """Build one validation row per sensor type."""
    grouped: dict[str, list[dict[str, object]]] = {}

    for row in observation_rows:
        sensor_type = str(row["sensor_type"])
        grouped.setdefault(sensor_type, []).append(row)

    output_rows: list[dict[str, object]] = []
    for sensor_type in sorted(grouped):
        output_rows.append(
            _summarize_observation_group(
                rows=grouped[sensor_type],
                label_fields={
                    "tipo_sensor": _format_sensor_type_for_output(sensor_type),
                },
            )
        )

    return output_rows


def _build_system_validation_summary(
    summary_rows: list[dict[str, object]],
) -> list[dict[str, object]]:
    """Build a one-row run-level validation summary aggregated over the full period."""
    precipitation_sum = np.asarray([float(row["precipitation_sum_mm_dt"]) for row in summary_rows], dtype=float)
    precipitation_max = np.asarray([float(row["precipitation_max_mm_dt"]) for row in summary_rows], dtype=float)
    pet_mean = np.asarray([float(row["pet_mean_mm_dt"]) for row in summary_rows], dtype=float)
    aet_mean = np.asarray([float(row["aet_mean_mm_dt"]) for row in summary_rows], dtype=float)
    surface_runoff_sum = np.asarray([float(row["surface_runoff_sum_mm_dt"]) for row in summary_rows], dtype=float)
    subsurface_runoff_sum = np.asarray([float(row["subsurface_runoff_sum_mm_dt"]) for row in summary_rows], dtype=float)
    outlet_discharge = np.asarray([float(row["outlet_discharge_m3s"]) for row in summary_rows], dtype=float)
    reservoir_storage_sum = np.asarray([float(row["reservoir_storage_sum_m3"]) for row in summary_rows], dtype=float)

    obs_available = np.asarray([float(row["obs_available_count"]) for row in summary_rows], dtype=float)
    obs_missing = np.asarray([float(row["obs_missing_count"]) for row in summary_rows], dtype=float)
    obs_censored = np.asarray([float(row["obs_censored_count"]) for row in summary_rows], dtype=float)

    return [
        {
            "titulo_resumen": "Resumen agregado de validación del sistema",
            "descripcion_resumen": (
                "Este archivo resume el comportamiento de la ejecucion completa. "
                "Las variables con 'acumulada_periodo' representan sumas temporales sobre todos los pasos "
                "de metricas por paso ya agregadas en el CSV de resumen de la simulacion. "
                "Las variables con 'media_por_paso' representan medias temporales de esas metricas por paso."
            ),
            "numero_pasos": len(summary_rows),
            "precipitacion_acumulada_periodo_mm_dt": _safe_sum(precipitation_sum),
            "precipitacion_maxima_periodo_mm_dt": _safe_max(precipitation_max),
            "pet_acumulada_periodo_mm_dt": _safe_sum(pet_mean),
            "aet_acumulada_periodo_mm_dt": _safe_sum(aet_mean),
            "pet_media_por_paso_mm_dt": _safe_mean(pet_mean),
            "aet_media_por_paso_mm_dt": _safe_mean(aet_mean),
            "escorrentia_superficial_acumulada_periodo_mm_dt": _safe_sum(surface_runoff_sum),
            "escorrentia_subsuperficial_acumulada_periodo_mm_dt": _safe_sum(subsurface_runoff_sum),
            "caudal_maximo_salida_periodo_m3s": _safe_max(outlet_discharge),
            "almacenamiento_final_total_embalses_m3": (
                float(reservoir_storage_sum[-1]) if reservoir_storage_sum.size > 0 else float("nan")
            ),
            "observaciones_disponibles_media_por_paso": _safe_mean(obs_available),
            "observaciones_faltantes_media_por_paso": _safe_mean(obs_missing),
            "observaciones_censuradas_media_por_paso": _safe_mean(obs_censored),
        }
    ]


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    run_dir = args.run_dir.resolve()
    output_dir = args.output_dir.resolve() if args.output_dir is not None else run_dir / "validation"

    observation_csv_path, summary_csv_path = _resolve_validation_csv_paths(run_dir)

    observation_rows = _read_observation_rows(observation_csv_path)
    summary_rows = _read_summary_rows(summary_csv_path)

    by_sensor_rows = _build_observation_validation_by_sensor(observation_rows)
    by_type_rows = _build_observation_validation_by_type(observation_rows)
    system_rows = _build_system_validation_summary(summary_rows)

    by_sensor_path = output_dir / "validacion_observaciones_por_sensor.csv"
    by_type_path = output_dir / "validacion_observaciones_por_tipo.csv"
    system_path = output_dir / "resumen_validacion_sistema.csv"

    _write_csv(rows=by_sensor_rows, output_path=by_sensor_path)
    _write_csv(rows=by_type_rows, output_path=by_type_path)
    _write_csv(rows=system_rows, output_path=system_path)

    system = system_rows[0]

    n_total_observations = len(observation_rows)
    n_available_observations = sum(int(row["observation_available"]) for row in observation_rows)
    n_missing_observations = n_total_observations - n_available_observations
    n_censored_observations = sum(int(row["quality_flag"]) == 2 for row in observation_rows)

    missing_rate = 0.0 if n_total_observations == 0 else n_missing_observations / n_total_observations
    censored_rate = 0.0 if n_total_observations == 0 else n_censored_observations / n_total_observations

    print("Validación completada correctamente.")
    print(f"Directorio de ejecución: {run_dir}")
    print(f"CSV de observaciones leído desde: {observation_csv_path}")
    print(f"CSV de resumen leído desde: {summary_csv_path}")
    print(f"Observaciones disponibles: {n_available_observations} / {n_total_observations}")
    print(f"Tasa de observaciones faltantes: {missing_rate:.3f}")
    print(f"Tasa de observaciones censuradas: {censored_rate:.3f}")
    print(f"Caudal máximo de salida: {system['caudal_maximo_salida_periodo_m3s']:.6f} m3/s")
    print(f"Precipitación acumulada del periodo: {system['precipitacion_acumulada_periodo_mm_dt']:.6f} mm/dt")
    print(f"PET acumulada del periodo: {system['pet_acumulada_periodo_mm_dt']:.6f} mm/dt")
    print(f"AET acumulada del periodo: {system['aet_acumulada_periodo_mm_dt']:.6f} mm/dt")
    print(f"Salidas de validación escritas en: {output_dir}")


if __name__ == "__main__":
    main()
